In [12]:
import pandas as pd
import numpy as np

r_div = pd.read_csv('data/final/returns_rp_hedged.csv', index_col=0, parse_dates=True)
r_tbill = pd.read_csv('data/wrds/risk_free_rate.csv', index_col=0, parse_dates=True)
r_carry = pd.read_csv('data/final/carry_strategy_returns.csv', index_col=0, parse_dates=True)
r_dollar = pd.read_csv('data/final/dollar_strategy_returns.csv', index_col=0, parse_dates=True)
r_reversal = pd.read_csv('data/final/reversal_strategy_returns.csv', index_col=0, parse_dates=True)
r_momentum = pd.read_csv('data/final/momentum_strategy_returns.csv', index_col=0, parse_dates=True)

In [13]:
start = pd.concat([r_div, r_tbill, r_carry, r_dollar, r_reversal, r_momentum], axis=1, join='inner')
start.columns = ['r_div', 'r_tbill', 'r_carry', 'r_dollar', 'r_reversal', 'r_momentum']

In [11]:
# missing rows
missing_rows = start[start.isnull().any(axis=1)]
print(missing_rows)

            carry_returns  dollar_strat_ret         0         0
date
2002-01-31       0.009128         -0.009748       NaN       NaN
2002-02-28       0.008820          0.012732       NaN       NaN
2002-03-28       0.007383          0.015227       NaN       NaN
2002-04-30      -0.011491          0.030861       NaN       NaN
2002-05-31       0.004056          0.030809       NaN       NaN
...                   ...               ...       ...       ...
2006-09-29       0.014123         -0.008365       NaN  0.009027
2006-10-31       0.012977          0.017809       NaN  0.010194
2006-11-30       0.017224          0.016629       NaN  0.006784
2006-12-29       0.026966         -0.016015       NaN -0.001324
2024-12-31            NaN               NaN -0.038652  0.000532

[61 rows x 4 columns]

In [14]:
start

               r_div   r_tbill   r_carry  r_dollar  r_reversal  r_momentum
date
2007-03-30  0.000000  0.004209  0.047818  0.013852    0.026818    0.030066
2007-04-30  0.037512  0.003962  0.014574 -0.006038    0.027953    0.031457
2007-05-31  0.031547  0.003912  0.031907 -0.002841   -0.002544   -0.000778
2007-06-29 -0.024887  0.003776  0.018333  0.021488   -0.015960   -0.005888
2007-07-31 -0.024651  0.004255 -0.057653 -0.005007   -0.004534    0.004741
...              ...       ...       ...       ...         ...         ...
2024-07-31 -0.009976  0.004464 -0.057656  0.025166    0.033427    0.009571
2024-08-30 -0.008167  0.004380  0.003649  0.014296    0.007561   -0.029214
2024-09-30  0.024795  0.003826  0.027441 -0.022557    0.003756    0.000308
2024-10-31  0.006756  0.003752  0.003234 -0.025824   -0.011847    0.026433
2024-11-29  0.022610  0.003475 -0.006877 -0.014009    0.024766    0.026742

[213 rows x 6 columns]

In [23]:
# FInd a
# r_div = r_tbill + a(r_div - r_tbill) where annualized volatility of R_fund is 0.15
# a * std(r_div - r_tbill) * (12)^(1/2) = 0.15
annualized_volatility = 0.15

r_div_tbill = start['r_div'] - start['r_tbill']
std_div_tbill_annual = r_div_tbill.std() * np.sqrt(12)  # annualized standard deviation
a = annualized_volatility / std_div_tbill_annual
print(f"a = {a:.4f}")

a = 1.1476

In [ ]:
# risk parity returns of the dynamic stock index strategies (MOM, REV) and the currency strategies (CARRY, DOLLAR)